package:
    name: foxbms
    version: "0.1"

source:
    path: ..

build:
    number: 1
    osx_is_app: True
    entry_points:
        - foxconfig = foxbms.configure:main
        - foxbms = foxbms.foxfdd:main
        - foxygen = foxbms.foxygen:main

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - wxpython
        - docutils
        - foxbmsflashtool
        - pyyaml
        - appdirs

about:
    home: http://www.foxbms.org
    license: BSD
    license_file: LICENSE

